app/yarn.lock
package.json
yarn.lock

When using Node 8.x, the following error was triggered when starting `yarn run dev`:
```
>> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
>> For more information on which environments are supported please see:
>> https://github.com/sass/node-sass/releases/tag/v4.5.1
```
This is due to packaged `node-sass` supporting Node runtime up to 7.x only (support for Node 8.x was [introduced in `node-sass 4.5.3`](https://github.com/sass/node-sass/pull/1969)).
This PR just bumps the `node-sass` version to let us use Ganache with Node 8.x 🍾

Upgrade node-sass to a version that supports Node 8.x

---

package.json
src/chain.js

Update to TestRPC v6.0.1

---

src/Services/Chain.js
src/chain.js

Turns out the `child_process` module emits an event when the child process exits. Switched to using this for monitoring whether the process is alive. Relying on request timeouts for detection of when the process has hung.

Replace heartbeat with start message & process exit event

---

src/Components/AppShell/AppShell.js
src/Components/AppShell/AppShell.scss
src/Components/AppShell/BugModal.js
src/Components/AppShell/BugModal.scss
src/Components/Helpers/sanitize.js
src/index.js

In order to give us more context when debugging user-submitted issues from the application, include up to the ~last 500 log lines~ in the bug report. [Edit: actually, 500 was too much, I made it so that it includes the last N log lines such that url encoding those lines doesn't exceed 7500 chars.] **This generates a GitHub issue which looks like the following example**:
PLATFORM: darwin
GANACHE VERSION: 1.6.11
EXCEPTION:
```
Blockchain process exited prematurely due to signal 'SIGTERM'.
```
APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"localhost","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+483ms: Ganache started successfully!
T+483ms: Waiting for requests...
```

Include last log lines in bug report

---

src/Components/Blocks/BlockCard.js

#268 Fixed mined on time formatting issue on BlockCard

---

package-lock.json

Add OS-specific optional dependecies of 7zip-bin to package-lock.json.
These entries were created using "npm install --package-lock-only".
This fixes #399.

Add optional dependencies to package-lock.json.

---

package-lock.json
package.json
src/Components/AppShell/AppShell.js
src/Components/AppShell/AppShell.scss
src/Components/Logs/LogContainer.js
src/Components/Logs/LogContainer.scss
src/app.global.scss

This PR adds the `react-custom-scrollbars` npm module to have better-looking scrollbars. The scrollbars have been added to the main page, wrapping everything in `ShellContainer`, as well as wrapping the `<li>` elements in `LogContainer`.
More documentation on this module can be found at https://github.com/malte-wessel/react-custom-scrollbars/tree/master/docs
Has been tested on Linux; see the below GIF.

Add Scrollbars to Main Pages

---

src/Components/Config/ConfigScreen.js
src/Components/Config/ConfigScreen.scss
src/Components/Config/ConfigScreens/AboutScreen.js
src/chain/chain.js

This PR replaces #235 as well as fixes #241.
The version number is added to the top of the Logs (and log file). An about screen is created and also displace the version number.

Add Version to Logs and Create About screen

---

src/Components/AutoUpdate/UpdateModal.js
src/Init/Renderer/AutoUpdate.js

This PR fixes a bug introduced in #712 (specifically https://github.com/trufflesuite/ganache/commit/e72d98193cbf26a2529cc24feb4e0129bd9f26ad#diff-003bb48b2c158c1250d7663a934b45ffL76) and fixes #831.

Fix AutoUpdate Issues

---

package-lock.json

Inspired by #857, this PR removes the `git://` URLs in `package-lock.json`. It doesn't appear to matter either way as `npm install` does work with the `git://` protocol.

Change websocket url to https instead of git

---

package-lock.json
src/Services/GoogleAnalytics.js
src/main.js

This PR addresses the issue of too much reporting to Google Analytics, causing us to go over the monthly 10M hits.
This PR moves the generic user data (location, checkProtocolTask, an, av) to another call instead of `setup` (which gets called in the analytics middleware for every event). This should roughly reduce the amount of hits by 80%

Reduce Google Analytics Hits

---

src/Services/Settings.js

Issue https://github.com/trufflesuite/ganache/issues/662
Default values used:
```
gasLimit: 6721975,
gasPrice: 20000000000
```

Issue 662: Set default settings when left blank

---

src/renderer/components/modal/ErrorModal.js
src/renderer/screens/config/ConfigScreens/WorkspaceScreen.js
src/renderer/screens/contracts/ContractCard.js

This PR implements using the error modals (see #921) as designed from the mockups. It just adds:
- A modal for removing a project in the config screen when the project has 1 or more **deployed** contracts
- A modal for trying to load the contract details of an undeployed contract

Implement Error Modals

---

src/common/redux/events/actions.js
src/common/redux/events/reducers.js
src/common/redux/workspaces/reducers.js
src/renderer/screens/contracts/ContractCard.js
src/renderer/screens/contracts/ContractDetails.js
src/renderer/screens/event-details/EventDetailsScreen.js
src/renderer/screens/events/EventItem.js
src/renderer/screens/events/EventList.js
src/renderer/screens/events/EventsScreen.js
src/renderer/screens/transactions/TxCard.js
src/renderer/screens/transactions/TxList.js

This PR implements the Events page without hardcoded values. Much of the logic was borrowed from the transactions page

Implement the Events Page without Hardcoding

---

src/renderer/index.js
src/renderer/screens/events/EventItem.js
src/renderer/screens/events/EventItem.scss

Related to #986. This pulls the same SCSS and dom structure from transaction cards (MiniTxCards) and copies that over to the event cards (EventItem).
Note that this is a bit of copy-pasta wrt CSS. 
There's likely more things we can do to dress up the event cards. This is probably good enough to close #986 and we dress it up more later.
Compare to the transaction card:

Format event cards

---

src/renderer/screens/config/ConfigScreens/ChainScreen.js

This PR fixes #1031. The below screenshot shows the disabled message:
This is how the accounts page is disabled, so I'm using the same look for gas limit for now.
Merging this myself. Leaving this here for posterity's sake.

Disable gas limit for workspaces

---

package-lock.json
package.json
src/Components/Config/ConfigScreen.js
src/Components/Config/ConfigScreens/AccountsScreen.js
src/Components/Config/ConfigScreens/ChainScreen.js
src/Components/Config/ConfigScreens/ServerScreen.js
src/chain/logging.js

I'm going to merge this on my own, but creating this PR for posterity's sake.
We opted out of releasing `v1.2.3` the last time around (October-ish) time frame due to an unstable `ganache-core` release. `ganache-core` has stabilized, so we'd like to release `v1.2.3` now.
In addition to bumping the version of `ganache-core`, there were a couple of issues/PRs that were addressed in the `2.x` codebase that we'd like to include in the `1.x` codebase since `v2.0.0` hasn't been released yet (still in beta). This PR implements the following fixes:
- #949
- Commit https://github.com/trufflesuite/ganache/commit/505af46ba3fe2acb422285841dd59e4477193e50 which addresses issue #1059 (originally addressed issue #1012)

Better v1.2.3

---

src/truffle-integration/index.js
src/truffle-integration/projectDetails.js
src/truffle-integration/projectFsWatcher.js
src/truffle-project-loader/index.js

This PR fixes #1076 by using a separate process which uses the `span("node")` function instead of `fork()` for running the `require()` on a Truffle project. This will use the system-installed version of node rather than the packaged version that comes with electron.

`require()` Truffle Project Configs in a Separate Process which Has No Native Dependencies

---

src/common/redux/middleware/analytics/engines/GoogleAnalytics.js
src/main/main.js

This PR is based off #1088 to prevent merge conflicts. I would consider this blocked by #1088
You can find the compare of the changes I made here: https://github.com/trufflesuite/ganache/compare/5419345...bug/fix-google-analytics
In 2.x, we changed `state.config.settings` to be split into `state.config.settings.workspace` and `state.config.settings.global`. The one place that the change was not updated was in the Google Analytics reporting.
For some reason `process.env.NODE_ENV` was reporting as `undefined`. This PR changes `main.js` to use `isDevMode` flag instead to enable Google Analytics for generic user data.
This PR fixes those problems

Fix Google Analytics Reporting for 2.x

---

src/renderer/screens/transactions/TxCard.js

Fixes #298 
Has a side effect of the following:
1. Go inside a tx (call this tx 1)
1. Search for a different tx (tx 2) while on tx 1 screen.
1. Tx 2 screen will show
1. Pressing back button will take you to tx 1 screen.
1. Pressing back again will take you to tx list screen.
Not sure what the intended behaviour is here. Did we want to take people back to the full tx list on press of back button? @DiscRiskandBisque 
Regardless, I think that's a job for another issue, if this isn't the desired UX.

Fix search for tx hash inside tx screen not working

---

src/main/main.js

Mac: Fix not closing all processes when closing app from dock

---

package-lock.json
package.json
src/common/services/TruffleIntegrationService.js
src/main/main.js
src/truffle-integration/projectDetails.js

Fixes https://github.com/trufflesuite/ganache/issues/1141
https://github.com/trufflesuite/ganache/commit/7042edd1958e808bd804d3521b96893604051611 introduced a bug for production (but not development) builds. The commit changed the way Truffle projects were loaded by running a completely separate node process thats installed on the user's machine to make sure that the node that was loading the Truffle project would be the same version that the Truffle project was "compiled" against.
Unfortunately the directory structure built with asar packing in production doesn't actually exist on the disk so the location can't actually be loaded by node. First we needed to specify that the project loader gets unpacked to the disk by adding it into the `build.extraFiles` config in `package.json`. Then we …

Ensure the Truffle Project Loader can be loaded in both development and production

---

package-lock.json
package.json
src/truffle-integration/projectDetails.js

Apparently the fix in #1149 doesn't work fully for the `Appx` distributable. Windows gives a `EPERM: operation not permitted, lstat 'C:\Program Files\WindowsApps'` error. The unpacked version for Appx is put into a subfolder of this system-protected folder and therefore the `node` process doesn't have access to reading the file. To circumvent the issue, this PR will write the contents of this file to a `temp.mkdirSync()` temporary directory (and should be removed automatically) which the `node` process can access.
This approach is being used for all OS's despite only needed for Windows Appx to keep the execution path similar across platforms.

Write Truffle Project Loader Script to Temp Directory to Circumvent Windows Permission Issues

---

src/renderer/screens/contracts/ContractsScreen.js
src/truffle-integration/projectDetails.js

Fixes #1165 by loading the `~/.nvm/nvm.sh` script in a `bash` shell session to get the default node version. It then adds `~/.nvm/versions/node/${version}/bin` to `process.env.PATH` and tries to load the project again. It only retries once.

add retry logic by manually finding the node path for nvm

---

src/renderer/screens/startup/HomeScreen.js

Keeping the link to the explanation of major changes is probably more useful than changing the link to the latest patch changelog, so this updates the link text instead, for accuracy.

v2.0.0 is no longer "the latest update"

---

package-lock.json
package.json
src/truffle-integration/projectsWatcher.js

Contract events weren't showing up for users of `truffle@1.0.17` and higher due to a commit that removed the event's signature from migrated contract abis: https://github.com/trufflesuite/truffle/pull/1949
This PR fixes this issue by creating the event signature locally if it isn't already supplied in the abi.
Fixes #1293

fix:make events display again

---

src/integrations/corda/main/utils/network/corda.js
src/integrations/corda/main/utils/network/manager.js
src/integrations/corda/renderer/screens/config/ConfigScreens/NodesScreen.js
src/integrations/index.js
src/main/index.js
src/renderer/routes.js
src/renderer/screens/config/ConfigScreen.js

This PR fixes #1560. 
This fix required more changes than I expected, so I wanted to quickly detail a few of the items:
https://github.com/trufflesuite/ganache/blob/da8bfa26ee7d03860b60fb1d826810a5b186f96e/src/integrations/corda/main/utils/network/corda.js#L292-L297
This change in `corda.js` defines the data necessary to trigger actions on the frontend, after the error gets bubbled all the way up. The important items are the `tab`, `key`, and `value`:
- `tab` is the route name of the Config tab that you want to be active when the error is shown. In the case where the route name of the tab has a slash, like `corda/nodes`, use the suffix `nodes`. (This is important in the tab detection discussed below.)
- `key` is an arbitrary key that the specific Config screen is set to show, if a …

Fix #1560 - show config screen when port-bind errors occur on startup

---

src/common/redux/workspaces/actions.js
src/integrations/index.js
src/main/index.js
src/main/types/workspaces/Workspace.js
src/main/types/workspaces/WorkspaceManager.js
src/renderer/screens/appshell/TopNavbar.js

feat: quickstart quick save

---

src/main/types/workspaces/WorkspaceManager.js

fixes #2018
fixes #2006
fixes #2000
fixes #1867
fixes #1758

fix: don't crash if OSX's .DS_Store dir exists

---

src/main/index.js

fixes #2057
fixes #2055
fixes #2050
fixes #2048
fixes #2036
fixes #1985
fixes #1971
fixes #1960
fixes #1950
fixes #1944
fixes #1909
fixes #1897
fixes #1880
fixes #1839
fixes #1834
fixes #1817
fixes #1776
fixes #1767

fix(windows): fix appx install on non-OS drive

---

.eslintrc.js
src/integrations/ethereum/renderer/screens/transactions/DestinationAddress.js
src/integrations/ethereum/renderer/screens/transactions/TransactionTypeBadge.js

Previously a "value transfer" transaction was shown as a "contract call", and the "to address" was shown as "contract address".
With this change, the correct label "value transfer" is shown, along with "to address".

fix: corrects the "value transfer" label, and "to address" in transaction list

---

src/main/index.js

When loading the workspace configuration screen, we immediately start the chain. This does actually makes sense, as the chain is a wrapper around Ganache which forks the nodejs process.
Previously we also immediately called `startServer()` which actually starts the Ganache instance. Now we only call `startServer()` when actually starting the Workspace.

Don't start the chain server when loading the configuration screen

---

package-lock.json
package.json
src/renderer/screens/startup/HomeScreen.js

The tooltip from `react-tooltip` will overflow the container (which is problematic within the context of the workspaces list).

Use react-tooltip component for homescreen tooltip

---

src/integrations/ethereum/common/services/EthereumChainService.js
src/integrations/filecoin/common/services/FilecoinChainService.js

Fixes a couple of different issues, including populating the network interfaces dropdown, and the `forked networks` header

Correctly resolve the response from `serverStart()`

---

src/main/index.js
src/main/init/migration.js
src/main/types/workspaces/Workspace.js
src/main/types/workspaces/WorkspaceManager.js

This changes the workspaces directory to `<config>/Ganache/ui/workspaces` in anticipation of all Ganache-UI configuration data being migrated to the `<config>Ganache/ui` directory. This means that previous versions of Ganache-UI will not have visibility to "new" workspaces. 
During the "migration" phase of startup, all workspaces in the "old" location will have symlinks created in the "new" location - meaning that "old" workspaces are available in the "new" version of Ganache-UI.
Deleting workspaces in either version of Ganache-UI will cause the workspace to be deleted for both.

fix: move workspaces to `Ganache/ui/workspaces`

---

package-lock.json
package.json
src/integrations/ethereum/common/redux/core/reducers.js
src/integrations/ethereum/renderer/screens/config/ConfigScreens/ChainScreen.js
src/main/types/settings/flavors/ethereum.js
static/node/package-lock.json
static/node/package.json

Adds support for the Berlin, London, Arrow Glacier, Gray Glacier and Merge hardforks.
Default is now "Merge" which is consistent with the `Ganache` CLI.

Add supported hardforks up to Merge.

---

src/renderer/screens/startup/HomeScreen.js

When loading the home screen, the previously selected flavor is always selected by default - for instance, if the user last started a "Filecoin" workspace, then the "Filecoin" flavor would be selected.
Before to this change, if the previously selected flavor was no longer supported (ie "Corda"), it would still be selected. Starting the workspace would cause an error "Workspace not found" to be thrown.
This change causes the default ("Ethereum") workspace to be selected if the previously selected flavor is no longer supported.

Only use the last selected flavor if it is supported

---

src/integrations/ethereum/renderer/screens/config/ConfigScreens/ServerScreen.js
src/integrations/index.js
static/node/chain/chain.ethereum.js

If no fork block is supplied when configuring the chain, the fork block number should be propagated back from chain service, persisted to `Settings` and presented in the UI.
Previously this was not happening, and the workspace would fork latest every time it were started.

fix: Fork block number doesn't get populated

---

src/main/index.js
src/main/init/migration.js
src/main/types/workspaces/Workspace.js
src/main/types/workspaces/WorkspaceManager.js

Previously to this change, running a `Quickstart` Ethereum workspace would cause the same workspace to no longer work in previous versions of Ganache due to the `hardfork` parameter becoming invalid.

fix: all user configuration data now lives in `Ganache/ui`

---

src/main/init/migration.js

In this release (v2.7.0) we have updated the signing certificate to one with a new CN, which may result in duplicate installations of Ganache UI (it may also fail to install, in which case the old version must first be uninstalled). This issue on MSIX packaging describes the issue: https://github.com/microsoft/msix-packaging/issues/365.
As a workaround, when the new version of Ganache UI is launched, it will check for old versions, and remove them if they exist.

fix: On first load, remove installations of Ganache >= 2.3.0 < 2.7.0

---

src/integrations/ethereum/common/services/TruffleIntegrationService.js

In some cases, when decoding a transaction, Ganache UI will throw an error, with the message Cannot read property 'stack' of undefined.
Specifically, the transaction must call a function that is not defined in the contract artifacts. This can be reproduced by defining and calling a `fallback` function.
This change fixes the issue, by correctly handling errors from the decoder. This means that if the above conditions are met, the decoded transaction promise resolves to undefined, which causes the caller to render the raw data.
See #5332 for a similar fix for decoding events.
Fixes: #5331
Fixes: #5328
Fixes: #5326
Fixes: #5323
Fixes: #5294
Fixes: #5278
Fixes: #5268
Fixes: #5227
Fixes: #5247
Fixes: #5207
Fixes: #5167
Fixes: #5158
Fixes: #5194
Fixes: #5277
Fixes: #5133
Fixes: #5055
Fixes: …

fix: correctly handle errors from transaction decoder

---

src/integrations/ethereum/common/services/TruffleIntegrationService.js

In some cases, when decoding an event, Ganache UI will throw an error, with the message `Cannot read property 'stack' of undefined`.
Specifically, if three conditions are met:
- There must be a subscription to the event identifier. This happens if there has been a contract artifact loaded which defines an event with a matching signature, but as per condition 3, that contract must not exist in the artifacts.
- There must be a contract artifact loaded, which is deployed to the address that raises the event
- The contract artifacts must not declare an event with a matching signature.
Further details can be seen here: https://github.com/jeffsmale90/ganache-ui-stack-repro
This change fixes the issue, by correctly handling errors from the decoder. This means that if the above conditions are …

fix: correctly handle errors from event decoder
