trufflesuite/ganache-ui

README.md
On windows it is necessary to have the Visual C++ component "VCBuild.exe" . This can be accomplished with the committed amendments.
=> Update README.md with additional windows pre-reqs

package-lock.json, package.json, src/Actions/Accounts.js, src/Actions/Blocks.js, src/Actions/Core.js, src/Actions/Search.js, src/Actions/Transactions.js, src/Actions/Web3.js, src/Actions/helpers/ReduxWeb3Provider.js, src/Actions/helpers/Web3ActionCreator.js, src/Components/Accounts/AccountList.js, src/Elements/ChecksumAddress.js, src/Kernel/ready.js, src/Reducers/Core.js, src/Reducers/Web3.js, src/chain.js, src/main.js
It's all in the title, really.
=> Updates Ganache UI to use web3 1.0, fixes trufflesuite/ganache-cli#457

src/Components/AppShell/BugModal.js, src/Components/Title/TitleScreen.js, src/Services/Chain.js, src/chain.js, src/main.js
=> Fix handling of uncaught errors from chain.js. Fixes #344

src/Components/Accounts/MnemonicAndHdPath.js, src/Components/Accounts/MnemonicAndHdPath.scss, src/Components/Accounts/MnemonicInfoModal.js, src/Components/Accounts/MnemonicInfoModal.scss, src/Elements/Modal.scss, src/index.js
This adds a warning/information modal to the `persistent-random-mnemonic` branch (#378). Screenshot below:
=> Add mnemonic information and warning message

package.json
New release fxes some bugs.
Thank you for contributing! Take a moment to review our [**contributing guidelines**](https://github.com/trufflesuite/ganache/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.
**IMPORTANT**: By submitting a patch via a Pull Request, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/trufflesuite/ganache/blob/master/LICENSE.md).
=> Update ganache-cli dependency

src/main.js
From issue #839 
Hi, 
I love the truffle framework. I've just updated two lines to fix a broken link that point to an old URL.
Just a silly bug. 
I hope it could help. 
Thank you for your efforts to bring to the world such wonderful suite of programs.
Best regards.
---------------------------------------------------------------------------------------------------
Thank you for contributing! Take a moment to review our [**contributing guidelines**](https://github.com/trufflesuite/ganache/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.
**You must open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something …
=> Update broken link. (From issue #839)

package.json, src/renderer/index.js, src/renderer/screens/appshell/TopNavbar.js, src/renderer/screens/contracts/ContractDetails.js, src/renderer/screens/contracts/ContractDetailsScreen.scss, src/renderer/screens/events/EventList.scss, src/renderer/screens/transactions/MiniTxCard.scss
@davidmurdoch worked this effort; I'm merging this into `feat/contract-introspection` to continue development. This PR is for historical purposes as I will delete David's branch.
=> WIP: Add and style ContractDetails screen

package-lock.json, package.json, src/common/redux/transactions/actions.js, src/common/redux/transactions/reducers.js, src/common/redux/workspaces/actions.js, src/common/services/TruffleIntegrationService.js, src/main/main.js, src/renderer/screens/transactions/TxCard.js, src/truffle-integration/decode.js, src/truffle-integration/index.js
This PR adds decoding for transaction details
=> Decode Transaction Details

src/common/redux/events/actions.js, src/common/redux/events/reducers.js, src/common/redux/reducer.js, src/common/redux/transactions/actions.js, src/common/redux/workspaces/actions.js, src/main/main.js, src/renderer/screens/contracts/ContractsScreen.js, src/renderer/screens/contracts/ContractsScreen.scss, src/renderer/screens/event-details/DecodedEventDetails.js, src/renderer/screens/event-details/EncodedEventDetails.js, src/renderer/screens/event-details/EventDetailsScreen.js, src/renderer/screens/transactions/TransactionTypeBadge.js
Merge #925 first, then this can be reviewed/merge
This PR implements event detail decoding
=> Decode Event Details

package-lock.json, src/common/redux/events/actions.js, src/common/redux/transactions/actions.js, src/common/redux/workspaces/actions.js, src/renderer/screens/contracts/ContractDetails.js, src/renderer/screens/event-details/DecodedEventDetails.js, src/renderer/screens/event-details/EncodedEventDetails.js, src/renderer/screens/event-details/EventDetailsScreen.js, src/renderer/screens/events/EventItem.js, src/renderer/screens/events/EventList.js, src/renderer/screens/events/RecentEvents.js, src/renderer/screens/transactions/TxCard.js
This PR implements the `Block Time` field for events
Should be merged after #944
=> Event block time

package-lock.json, src/common/redux/core/actions.js, src/common/redux/workspaces/actions.js, src/renderer/index.js, src/renderer/init/Core.js, src/renderer/screens/loader/LoaderScreen.js, src/renderer/screens/loader/LoaderScreen.scss
This PR adds a placeholder screen. It's meant to be shown when things are loading before changing the screen. It's ideal as it does not use any state.
The design definitely can change. It looks identical to the old title screen (fade in Ganache logo with version number). I'm going to go ahead in merge this however, but I encourage @DiscRiskandBisque or @adrianmcli to provide any feedback/changes before 2.0 is released.
=> Loader screen

src/renderer/screens/contracts/ContractDetails.js, src/renderer/screens/contracts/ContractDetailsScreen.scss, src/truffle-integration/decode.js, src/truffle-integration/index.js
This PR adds error handling for exceptions when trying to decode a contract's state. This is what the message looks like:
This is for issue #1016
I'm going to go ahead and merge this due to lack of reviewing capacity, but I'm going to CC @DiscRiskandBisque and @honestbonsai if they would like to peruse these changes.
=> Decoding error handling

package-lock.json, src/common/redux/events/actions.js, src/renderer/screens/transactions/TxCard.js
Fixes #1026 
I'm going to merge this PR however; it's existence is for posterity's sake.
=> Make sure we use the correct address/contract for events

src/renderer/screens/config/ConfigScreen.js, src/renderer/screens/config/ConfigScreens/AccountsScreen.js, src/renderer/screens/config/ConfigScreens/ChainScreen.js, src/renderer/screens/config/ConfigScreens/ServerScreen.js
This PR fixes and should close #948
=> fix issue where 0 is alway prepended in blocktime textfield

src/renderer/screens/config/ConfigScreens/WorkspaceScreen.js
=> Make it more obvious what file to add to link truffle project

package-lock.json, package.json, src/common/redux/core/reducers.js, src/common/services/GoogleAnalyticsService.js, src/main/types/settings/WorkspaceSettings.js, src/renderer/screens/appshell/TopNavbar.js, src/renderer/screens/config/ConfigScreens/ChainScreen.js
There are some changes that were required by the linter mixed in here as well:
```
( •_•)
( •_•)>⌐■-■
(⌐■_■)
```
=> Update ganache-core to v2.4.0 and add HARDFORK option to settings

src/renderer/screens/transactions/TxList.js
=> Fix No Transactions not being centered

package-lock.json, package.json, src/common/redux/core/reducers.js, src/main/types/settings/WorkspaceSettings.js, src/renderer/screens/config/ConfigScreens/ChainScreen.js
=> Update to ganache-core@2.5.3 and add petersburg fork default setting

src/renderer/screens/config/ConfigScreens/ChainScreen.js
=> Support a gas price of 0

src/renderer/screens/config/ConfigScreen.scss, src/renderer/screens/config/ConfigScreens/WorkspaceScreen.js
=> Fix truffle project list background overflow bug

src/common/redux/web3/actions.js, src/renderer/init/Core.js
Tested on Windows 10 x64.
Fixes #1172, #1173, #1179, #1191, and #1194.
=> Make sure we always use the correct interface for web3 connections

src/main/types/workspaces/Workspace.js
=> fix: contract cache migration conflict

src/main/types/workspaces/Workspace.js
fixes #2031
fixes #2023
fixes #1978
fixes #1957
fixes #1945
fixes #1774
=> fix: ensure all workspaces have a sanitized name

src/renderer/components/file-picker/FilePicker.js
=> fix: select directory, not file, for log location

src/integrations/ethereum/renderer/screens/blocks/BlockCard.scss, src/integrations/ethereum/renderer/screens/blocks/BlockList.js, src/integrations/filecoin/common/redux/tipsets/actions.js, src/integrations/filecoin/renderer/screens/accounts/AccountList.scss, src/integrations/filecoin/renderer/screens/config/ConfigScreens/ServerScreen.js, src/integrations/filecoin/renderer/screens/deals/DealList.js, src/integrations/filecoin/renderer/screens/files/FilesScreen.js, src/integrations/filecoin/renderer/screens/files/MiniFileCard.scss, src/integrations/filecoin/renderer/screens/tipsets/BlockCard.scss, src/integrations/filecoin/renderer/screens/tipsets/TipsetList.js, src/renderer/init/ErrorHandler.js, src/renderer/styles/logo.scss
This PR is a small set of bug fixes and miscellaneous styling requests that I/@tcoulter found.
=> fix(filecoin): miscellaneous bug fixes and styling requests

src/integrations/filecoin/renderer/screens/files/MiniFileCard.js
This PR will set the save dialog's default file name to the IPFS `file.name` if it's set
=> feat(filecoin): set the filename on download to the file.name if it's set

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, LICENSE, README.md, package.json, src/integrations/ethereum/renderer/screens/contracts/ContractDetails.js, src/renderer/screens/appshell/BugModal.js, src/renderer/screens/appshell/TopNavbar.js, src/renderer/screens/auto-update/UpdateModal.js, src/renderer/screens/startup/HomeScreen.js
Fixes links to old github project. Also adds LICENSE file.
=> Fix old github project links
